config:
  alerting:
    slack:
      webhook-url: "https://hooks.slack.com/services/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"
      default-alert:
        description: "health check failed"
        send-on-resolved: true
        failure-threshold: 5
        success-threshold: 5
  endpoints:
    - name: Frontier                 # Name of your endpoint, can be anything
      url: "https://frontier.dev.brevanhoward.digital"
      interval: 30s                  # Duration to wait between every status check (default: 60s)
      conditions:
        - "[STATUS] == 200"         # Status must be 200
        - "[RESPONSE_TIME] < 100"   # Response time must be under 300ms
      
      alerts:
        - type: slack
          description: "Healthchecks failed 3 times in a row"
          send-on-resolved: true
        - type: slack
          failure-threshold: 5
          description: "Healthchecks failed 5 times in a row"
          send-on-resolved: true
        
    
    - name: Internal WhereamI service
      url: "http://foo.default.svc.cluster.local:8080"
      interval: 30s
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 300"
    
    - name: Internal WhereamI through Gateway
      url: "http://10.142.0.9"
      headers:
        Host: whereami.example.com
      interval: 30s
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 300"
    
    - name: Internal WhereamI service through Ingress
      url: "http://10.142.15.242"
      interval: 30s
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 300"

service:
  labels:
    app: gatus
  annotations:
    cloud.google.com/backend-config: '{"default": "gatus-backend-config"}'

ingress:
  enabled: true
  name: gatus-ingress
  annotations:
    kubernetes.io/ingress.class: gce
  labels:
    app: gatus
  hosts:
    - 'gatus.gats.dev'
